services:
  seq:
    image: datalust/seq
    ports:
    - "5341:80"
    environment:
      - ACCEPT_EULA=Y
  # mssql:
  #   image:  mcr.microsoft.com/azure-sql-edge:latest
  #   environment:
  #     - SA_PASSWORD=Episerver123!
  #     - ACCEPT_EULA=Y
  #   ports:
  #     - "1433:1433"